In [1]:
import numpy as np

arr = np.arange(1, 11)
print("1D array:", arr)

matrix = np.random.randint(1, 10, (3, 3))
print("2D array:\n", matrix)

print("Sum:", np.sum(arr))
print("Mean:", np.mean(arr))
print("Max:", np.max(arr))

arr2 = arr * 2
print("Multiplied by 2:", arr2)

arr[arr > 5] = 0
print("Replaced >5 with 0:", arr)


1D array: [ 1  2  3  4  5  6  7  8  9 10]
2D array:
 [[1 6 8]
 [6 9 8]
 [5 2 4]]
Sum: 55
Mean: 5.5
Max: 10
Multiplied by 2: [ 2  4  6  8 10 12 14 16 18 20]
Replaced >5 with 0: [1 2 3 4 5 0 0 0 0 0]
